# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.10
FROM ruby:${RUBY_VERSION}-alpine

RUN apk add --no-cache docker-cli docker-cli-compose && \
    docker --version && \
    docker compose version

WORKDIR /app

COPY lib/rundiff/subject ./lib/rundiff/subject
COPY script/compose_service_provider_server.rb ./script/compose_service_provider_server.rb

ENV RUNDIFF_COMPOSE_PROVIDER_SOCKET=/run/rundiff-provider/provider.sock

CMD ["ruby", "script/compose_service_provider_server.rb"]
