export interface Env {
  RUNDIFF_GITHUB_APP_ID?: string;
  RUNDIFF_GITHUB_APP_PRIVATE_KEY?: string;
  RUNDIFF_GITHUB_WEBHOOK_SECRET?: string;
  RUNDIFF_EXECUTOR_TIMEOUT_SECONDS?: string;
  RUNDIFF_EXECUTOR_LEASE_SECONDS?: string;
  RUNDIFF_EXECUTOR_AUTODISPATCH?: string;
  RUNDIFF_EXECUTOR_DISPATCH_REPOSITORY?: string;
  RUNDIFF_EXECUTOR_DISPATCH_WORKFLOW?: string;
  RUNDIFF_EXECUTOR_DISPATCH_REF?: string;
  DB: D1Database;
  ARTIFACTS: R2Bucket;
  REVIEW_WORKFLOW: Workflow;
  RUNDIFF_SPIKE_TOKEN?: string;
  RUNDIFF_GITHUB_ACTIONS_BRIDGE_TOKEN?: string;
}
