default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: rundiff_development

test:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://localhost/rundiff_test") %>
  queue:
    <<: *default
    url: <%= ENV.fetch("SOLID_QUEUE_DATABASE_URL", "postgres://localhost/rundiff_queue_test") %>
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV.fetch("SOLID_QUEUE_DATABASE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/queue_migrate
